########################################################################
### Composer

# Use the official PHP image with Apache
FROM php:8.0-apache

# Set the working directory inside the container
WORKDIR /var/www/html

# Install PHP extensions
RUN docker-php-ext-install mysqli
